# Generated by Django 2.1.3 on 2018-11-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_9432',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=30)),
                ('opening_price', models.CharField(max_length=30)),
                ('high_price', models.CharField(max_length=30)),
                ('low_price', models.CharField(max_length=30)),
                ('closing_price', models.CharField(max_length=30)),
                ('volume_price', models.CharField(max_length=30)),
                ('ad_closing_price', models.CharField(max_length=30)),
            ],
        ),
    ]
