# Generated by Django 2.1.3 on 2018-11-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='close_price',
            new_name='closing_price',
        ),
    ]
